// Run after npm run build. Install Chromium with: npx playwright install chromium.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { once } from 'node:events';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec = promisify(execFile);
const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'clip-studio-browser-'));
process.env.NODE_ENV='production';process.env.PORT='0';process.env.GEMINI_API_KEY='';
process.env.CANVA_CLIENT_ID='';process.env.CANVA_CLIENT_SECRET='';process.env.CANVA_ACCESS_TOKEN='';
process.env.CLIP_STUDIO_DATA_DIR=path.join(directory,'data');
const { start } = await import('../server.ts');
const { probeMedia } = await import('../server/media.ts');
const server=await start();await once(server,'listening');
const base = `http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH || undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--autoplay-policy=no-user-gesture-required'],headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));
let passed=0;
const log=name=>{passed++;console.log(`PASS ${name}`);};
const shown=async text=>{await page.getByText(text,{exact:false}).first().waitFor({state:'visible',timeout:20000});};
try {
  const audioFile=path.join(directory,'audio.wav'),imageFile=path.join(directory,'blue.png'),videoFile=path.join(directory,'background.mp4');
  await exec('ffmpeg',['-y','-v','error','-f','lavfi','-i','sine=frequency=550:sample_rate=48000:duration=4','-c:a','pcm_s16le',audioFile]);
  await exec('ffmpeg',['-y','-v','error','-f','lavfi','-i','color=c=blue:s=320x180:d=1','-frames:v','1',imageFile]);
  await exec('ffmpeg',['-y','-v','error','-f','lavfi','-i','testsrc2=size=320x180:rate=30:duration=4','-an','-c:v','libx264','-pix_fmt','yuv420p',videoFile]);
  await page.goto(base);await page.getByRole('button',{name:'Export .MP4',exact:true}).waitFor();
  await page.getByRole('button',{name:'Export .MP4',exact:true}).click();
  await page.getByRole('button',{name:'Export 1080P .MP4 Video',exact:true}).click();
  await shown('No audio is ready.');assert.equal(await page.getByText('MP4 Clip Rendered Successfully!',{exact:true}).count(),0);
  log('missing audio blocks export with an actionable error');
  await page.getByRole('button',{name:'Close',exact:true}).click().catch(async()=>{await page.locator('button').filter({has:page.locator('svg.lucide-x')}).last().click();});
  await page.getByRole('button',{name:'Audio/YT',exact:true}).click();

  await page.getByRole('button',{name:'Upload Audio',exact:true}).click();
  await page.locator('input[type=file][accept="audio/*,video/*"]').setInputFiles(audioFile);
  await shown('audio.wav');
  await page.getByTitle('Play',{exact:true}).click();await page.waitForTimeout(500);await page.getByTitle('Pause',{exact:true}).click();
  log('uploaded audio decodes and preview plays and pauses');
  await page.getByRole('button',{name:'Subtitles',exact:true}).click();
  await page.locator('input[type=file][accept=".srt,.vtt"]').setInputFiles({name:'captions.srt',mimeType:'text/plain',buffer:Buffer.from('1\n00:00:00,200 --> 00:00:02,200\nHello actual audio\n\n2\n00:00:02,200 --> 00:00:03,800\n123\n')});
  await page.waitForFunction(()=>document.querySelectorAll('textarea')[1]?.value==='123');
  assert.equal(await page.locator('textarea').nth(1).inputValue(),'123');
  const cueStart=page.locator('input[value="00:00.20"]');await cueStart.fill('00:00.50');await cueStart.press('Tab');assert.equal(await page.locator('input[value="00:00.50"]').inputValue(),'00:00.50');
  await page.getByRole('button',{name:'AI English (EN)',exact:true}).click();await page.getByRole('alert').waitFor({state:'visible'});assert.match(await page.getByRole('alert').innerText(),/Configure GEMINI_API_KEY/);
  assert.equal(await page.locator('textarea').first().inputValue(),'Hello actual audio');
  await page.getByRole('button',{name:'Dismiss',exact:true}).click();
  log('SRT import preserves numeric captions and failed AI leaves captions intact');
  // Set a nonzero trim start by dragging the existing timeline handle.
  const handle=page.getByTitle('Drag to adjust Trim Start');const box=await handle.boundingBox();
  const waveform=await handle.locator('..').boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(waveform.x+waveform.width*0.25,box.y+box.height/2,{steps:10});await page.mouse.up();
  await shown('Trim: 00:01 - 00:04');
  await page.getByRole('button',{name:'BG / Canva',exact:true}).click();
  await page.locator('input[type=file][accept="video/*,image/*"]').last().setInputFiles(imageFile);
  log('background image upload and nonzero timeline trim');
  const doExport=async(label,fileName,standard=false)=>{
    await page.getByRole('button',{name:'Export .MP4',exact:true}).click();
    await page.getByRole('button',{name:'720p HD',exact:true}).click();
    await page.getByRole('button',{name:'24 Film',exact:true}).click();
    await page.getByRole('button',{name:standard ? /Standard/ : /Turbo/}).click();
    await page.getByRole('button',{name:'Export 720P .MP4 Video',exact:true}).click();
    await shown('MP4 Clip Rendered Successfully!');
    const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download Video File (.MP4)',exact:true}).click();
    const result=await download;const file=path.join(directory,fileName);await result.saveAs(file);
    const info=await probeMedia(file);assert.ok(info.streams.some(s=>s.codec_type==='audio'&&s.codec_name==='aac'));
    const video=info.streams.find(s=>s.codec_type==='video');assert.equal(video.width,720);assert.equal(video.height,1280);assert.equal(video.avg_frame_rate,'24/1');assert.ok(Math.abs(info.duration-3)<0.15);
    const decoded=await exec('ffmpeg',['-v','error','-i',file,'-vn','-c:a','pcm_f32le','-f','f32le','pipe:1'],{encoding:'buffer',maxBuffer:5000000});
    let sum=0;for(let i=0;i<decoded.stdout.length;i+=4)sum+=decoded.stdout.readFloatLE(i)**2;assert.ok(Math.sqrt(sum/(decoded.stdout.length/4))>0.04);
    log(label);
    await page.getByRole('button',{name:'Close',exact:true}).click().catch(async()=>{await page.locator('button').filter({has:page.locator('svg.lucide-x')}).last().click();});
    return file;
  };
  const exported=await doExport('turbo browser export has audible AAC, 720p, 24 FPS and the trimmed duration','turbo.mp4');
  if(process.env.QA_OUTPUT_DIR) {await fs.mkdir(process.env.QA_OUTPUT_DIR,{recursive:true});await fs.copyFile(exported,path.join(process.env.QA_OUTPUT_DIR,'browser-export.mp4'));}
  await page.locator('input[type=file][accept="video/*,image/*"]').last().setInputFiles(videoFile);
  await doExport('standard browser export retains a real video background and audio','standard.mp4',true);
  await page.route('**/api/convert-mp4?*',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Test conversion failure'})}));
  await page.getByRole('button',{name:'Export .MP4',exact:true}).click();
  await page.getByRole('button',{name:'Export 720P .MP4 Video',exact:true}).click();
  await shown('Test conversion failure');assert.equal(await page.getByText('MP4 Clip Rendered Successfully!',{exact:true}).count(),0);
  log('failed conversion never produces a fake MP4 success');
  await page.unroute('**/api/convert-mp4?*');
  await page.getByRole('button',{name:'Export 720P .MP4 Video',exact:true}).click();await shown('Cancel Export');await page.getByRole('button',{name:'Cancel Export',exact:true}).click();
  await page.getByRole('button',{name:'Export 720P .MP4 Video',exact:true}).waitFor();assert.equal(await page.getByText('MP4 Clip Rendered Successfully!',{exact:true}).count(),0);log('cancel export returns safely to export settings');
  await page.getByRole('button',{name:'Close',exact:true}).click().catch(async()=>{await page.locator('button').filter({has:page.locator('svg.lucide-x')}).last().click();});
  // Exercise the YouTube browser import with real WAV bytes returned by a
  // controlled extraction response. Live YouTube authorization is separate.
  let requested;
  await page.route('**/api/youtube/prefetch',route=>route.fulfill({contentType:'application/json',body:'{"ok":true}'}));
  await page.route('**/api/youtube/info',async route=>{
    requested=route.request().postDataJSON();
    await route.fulfill({contentType:'application/json',body:JSON.stringify({videoId:'abcdefghijk',title:'YouTube Audio Fixture',author:'Test',audioBase64:(await fs.readFile(audioFile)).toString('base64'),duration:4,startTime:12.25,endTime:16.25,subtitles:[]})});
  });
  await page.getByRole('button',{name:'Audio/YT',exact:true}).click();await page.getByRole('button',{name:'YouTube Link',exact:true}).click();
  await page.getByPlaceholder('https://www.youtube.com/watch?v=... or youtu.be/...').fill('https://youtube.com/watch?feature=share&v=abcdefghijk');
  await page.getByPlaceholder('00:00',{exact:true}).fill('00:12.25');await page.getByPlaceholder('00:45',{exact:true}).fill('00:16.25');
  await page.getByRole('button',{name:'Pull Audio From Timeframe',exact:true}).click();await shown('Pulled audio "YouTube Audio Fixture"');assert.equal(requested.startTime,12.25);assert.equal(requested.endTime,16.25);
  const ytHandle=page.getByTitle('Drag to adjust Trim Start'),ytBox=await ytHandle.boundingBox(),ytWave=await ytHandle.locator('..').boundingBox();
  await page.mouse.move(ytBox.x+ytBox.width/2,ytBox.y+ytBox.height/2);await page.mouse.down();await page.mouse.move(ytWave.x+ytWave.width*0.25,ytBox.y+ytBox.height/2,{steps:10});await page.mouse.up();await shown('Trim: 00:01 - 00:04');
  await doExport('YouTube import with fractional timestamps exports the real decoded audio','youtube-fixture.mp4');
  await page.getByRole('button',{name:'Subtitles',exact:true}).click();
  await page.route('**/api/transcribe',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({subtitles:[{id:'timed',start:0,end:1,text:'Aligned transcript',words:[{word:'Aligned',start:0,end:0.5},{word:'transcript',start:0.5,end:1}]}]})}));
  await page.getByRole('button',{name:'AI English (EN)',exact:true}).click();await page.locator('textarea').first().filter({visible:true}).waitFor();await page.waitForTimeout(100);
  assert.equal(await page.locator('input[value="00:01.00"]').inputValue(),'00:01.00');log('transcription timings are shifted to the nonzero trim start');
  await page.unroute('**/api/transcribe');
  await page.route('**/api/youtube/info',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'YouTube extraction unavailable'})}));
  await page.getByRole('button',{name:'Audio/YT',exact:true}).click();await page.getByRole('button',{name:'YouTube Link',exact:true}).click();
  await page.getByRole('button',{name:'Pull Audio From Timeframe',exact:true}).click();await shown('YouTube extraction unavailable');log('failed YouTube imports display a clear error');
  await page.getByRole('button',{name:'BG / Canva',exact:true}).click();
  const popupPromise=page.waitForEvent('popup');await page.getByRole('button',{name:'BG Editor (Separate Window)',exact:true}).click();const popup=await popupPromise;await popup.waitForLoadState();
  await popup.locator('#bgTitle').fill('Edited Background Fixture');
  await popup.getByRole('button',{name:/Apply.*Background|Apply.*Clip/}).click();await shown('Edited Background Fixture');await popup.close();log('separate background editor applies its image back to the app');
  await page.getByRole('button',{name:'Connect Canva Account',exact:true}).click();
  await page.getByRole('button',{name:'OAuth Popup Login',exact:true}).click();
  await shown('Configure CANVA_CLIENT_ID and CANVA_CLIENT_SECRET');
  log('unconfigured Canva OAuth reports an error without claiming connection');
  await page.getByRole('button',{name:'n8n Post',exact:true}).click();
  const templateDownload = page.waitForEvent('download');
  await page.getByRole('button',{name:'.JSON',exact:true}).click();
  const templateFile = path.join(directory,'n8n-starter.json');
  await (await templateDownload).saveAs(templateFile);
  const template = JSON.parse(await fs.readFile(templateFile,'utf8'));
  assert.match(template.nodes.find(node=>node.type==='n8n-nodes-base.httpRequest').parameters.url,/body\.clip\.videoMp4Url/);
  const webhookInput = page.getByPlaceholder('https://your-instance.app.n8n.cloud/webhook/clip-studio-autopost');
  await webhookInput.fill('not-a-url'); await webhookInput.press('Tab');
  await shown('Invalid URL');
  assert.ok(await page.getByRole('button',{name:'Connect & Select at Least 1 Account Above',exact:true}).isDisabled());
  log('n8n starter downloads correctly and failed configuration saves are visible');
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Subtitles',exact:true}).click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));log('mobile layout stays within the viewport');
  assert.deepEqual(pageErrors,[]);log('no uncaught browser errors');
  console.log(`Browser checks passed: ${passed}`);
} catch(error) { if(process.env.QA_OUTPUT_DIR) await page.screenshot({path:path.join(process.env.QA_OUTPUT_DIR,'browser-failure.png'),fullPage:true}); console.log('Last screen:',(await page.locator('body').innerText()).slice(-1800));throw error; } finally { await browser.close();await new Promise(resolve=>server.close(resolve));await fs.rm(directory,{recursive:true,force:true}); }
